GET http://localhost:3000/clients
Content-Type: application/json

{
  "firstName": "Carlos",
  "lastName": "Rodríguez",
  "dni": "56789012",
  "phoneNumber": "+5491123456789",
  "email": "carlos.rodriguez@gmail.com",
  "address": "Montañas 101, Bariloche, Argentina"
}
